# Generated by Django 2.1.5 on 2019-02-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0011_auto_20180803_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='all_countries',
            field=models.BooleanField(default=False),
        ),
    ]
